# Generated by Django 3.2.5 on 2021-07-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article_image',
            new_name='post_image',
        ),
    ]
